City.create!([
  {prefecture_id: 25, name: '大津市'},
  {prefecture_id: 25, name: '彦根市'},
  {prefecture_id: 25, name: '長浜市'},
  {prefecture_id: 25, name: '近江八幡市'},
  {prefecture_id: 25, name: '草津市'},
  {prefecture_id: 25, name: '守山市'},
  {prefecture_id: 25, name: '栗東市'},
  {prefecture_id: 25, name: '甲賀市'},
  {prefecture_id: 25, name: '野洲市'},
  {prefecture_id: 25, name: '湖南市'},
  {prefecture_id: 25, name: '高島市'},
  {prefecture_id: 25, name: '東近江市'},
  {prefecture_id: 25, name: '米原市'},
  {prefecture_id: 25, name: '蒲生郡日野町'},
  {prefecture_id: 25, name: '蒲生郡竜王町'},
  {prefecture_id: 25, name: '愛知郡愛荘町'},
  {prefecture_id: 25, name: '犬上郡豊郷町'},
  {prefecture_id: 25, name: '犬上郡甲良町'},
  {prefecture_id: 25, name: '犬上郡多賀町'},
  ])