City.create!([
  {prefecture_id: 17, name: '金沢市'},
  {prefecture_id: 17, name: '七尾市'},
  {prefecture_id: 17, name: '小松市'},
  {prefecture_id: 17, name: '輪島市'},
  {prefecture_id: 17, name: '珠洲市'},
  {prefecture_id: 17, name: '加賀市'},
  {prefecture_id: 17, name: '羽咋市'},
  {prefecture_id: 17, name: 'かほく市'},
  {prefecture_id: 17, name: '白山市'},
  {prefecture_id: 17, name: '能美市'},
  {prefecture_id: 17, name: '野々市市'},
  {prefecture_id: 17, name: '能美郡川北町'},
  {prefecture_id: 17, name: '河北郡津幡町'},
  {prefecture_id: 17, name: '河北郡内灘町'},
  {prefecture_id: 17, name: '羽咋郡志賀町'},
  {prefecture_id: 17, name: '羽咋郡宝達志水町'},
  {prefecture_id: 17, name: '鹿島郡中能登町'},
  {prefecture_id: 17, name: '鳳珠郡穴水町'},
  {prefecture_id: 17, name: '鳳珠郡能登町'},
  ])