City.create!([
  {prefecture_id: 38, name: '松山市'},
  {prefecture_id: 38, name: '今治市'},
  {prefecture_id: 38, name: '宇和島市'},
  {prefecture_id: 38, name: '八幡浜市'},
  {prefecture_id: 38, name: '新居浜市'},
  {prefecture_id: 38, name: '西条市'},
  {prefecture_id: 38, name: '大洲市'},
  {prefecture_id: 38, name: '伊予市'},
  {prefecture_id: 38, name: '四国中央市'},
  {prefecture_id: 38, name: '西予市'},
  {prefecture_id: 38, name: '東温市'},
  {prefecture_id: 38, name: '越智郡上島町'},
  {prefecture_id: 38, name: '上浮穴郡久万高原町'},
  {prefecture_id: 38, name: '伊予郡松前町'},
  {prefecture_id: 38, name: '伊予郡砥部町'},
  {prefecture_id: 38, name: '喜多郡内子町'},
  {prefecture_id: 38, name: '西宇和郡伊方町'},
  {prefecture_id: 38, name: '北宇和郡松野町'},
  {prefecture_id: 38, name: '北宇和郡鬼北町'},
  {prefecture_id: 38, name: '南宇和郡愛南町'},
  ])